config/routes.rb
FailinGs::Application.routes.draw do
  resource :user_session, except: :update
  get "login", to: "user_sessions#new", as: :login
  match "logout", to: "user_sessions#destroy", method: :delete, as: :logout

  match 'auth/failure',            to: 'authentications#failure'
  match 'auth/:provider/callback', to: 'authentications#callback'
  match 'auth/:provider/unlink',   to: 'authentications#unlink'
  match 'auth/:provider/destroy',  to: 'authentications#destroy',
    as: :auth_delete

  resource :account, controller: "users", only: %w(create edit update destroy) do
    get  "unsubscribe" => "users#unsubscribe",  as: :unsubscribe
    post "unsubscribe" => "users#unsubscribed", as: :unsubscribed
  end
  get  "account" => redirect("/account/edit")

  resources :preferences

  resource :password, only: %w(new create edit update destroy)

  scope "profile/:login" do
    resources :failings, only: %w(create show) do
      member do
        put :knew
        put :no_idea
        put :disagree
      end

      resources :comments, only: %w(create) do
        resource :abuse, only: %w(create)
      end
      resource :vote, only: %w(create)
      resource :abuse, only: %w(create)
    end
  end

  resources :friends, only: %w(index create destroy) do
    collection do
      get :bookmarks
      get :twitter
      get :facebook
      # get :email
    end
  end

  resource :invitation, only: %w(new create)
  get "invitation/search", to: "invitations#search", as: :search

  resource :share, only: %w(new create)
  resource :email, only: %w(create)

  get "profile/:login(.:format)", to: "failings#index", as: :profile
  get "profile/:login/failings" => redirect("/profile/%{login}")

  get "pages/:action", to: "pages", action: /[a-z-]+/, as: :page

  # get "javascripts/:action.:format" => "javascripts"
  get "stylesheets/:action.:format" => "stylesheets"

  mount Resque::Server.new, at: 'resque'

  root to: "pages#root"

  get ":login" => redirect("/profile/%{login}")
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :require_user

  def create
    render :update do |page|
      if @user = User.find_by_login(params[:user_id])
        current_user.bookmarked << @user unless current_user.bookmarked.include? @user

        page << "if ($('#{dom_id @user, :bookmark}')) {"
        page[dom_id(@user, :bookmark)].replace partial: "failings/bookmark", object: @user
        page << "}"
        page << "bindBookmarkEvents();"
      end
    end
  end

  def destroy
    render :update do |page|
      @user = User.find_by_login params[:user_id]
      if current_user.bookmarked.include?(@user)
        current_user.bookmarked.delete(@user)

        page << "if ($('#{dom_id @user, :bookmark}')) {"
        page[dom_id(@user, :bookmark)].replace partial: "failings/bookmark", object: @user
        page << "}"

        page << "bindBookmarkEvents();"

        page << "if ($('sub_nav_body') && $$('ul.bookmarks li').length === 0) {"
        page[:sub_nav_body].replace_html partial: "no_bookmarks"
        page << "}"
      end
    end
  end

  def twitter
    if current_user.twitter?
      @friends   = current_user.twitter_friends
      @followers = current_user.twitter_followers
    end
  end

  def facebook
    if current_user.facebook?
      @friends = current_user.facebook_friends
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_bookmark.html.erb
<li>
  <%= link_to bookmark.login, profile_path(bookmark), class: "bookmark on" %>
  <%= link_to "delete?", friend_path(bookmark, user_id: bookmark.login), method: :delete, remote: true, class: "delete", style: "display: none;" %>
</li>

app/views/friends/_facebook_friend.html.erb
<li>
  <%= link_to avatar_for(facebook_friend, size: 50), profile_path(facebook_friend) %>
  <%= facebook_friend["facebook_name"] %>
  <%= link_to facebook_friend.login, profile_path(facebook_friend) %>
  <%= render partial: "failings/bookmark", object: facebook_friend %>
</li>

app/views/friends/_friends_headline.html.erb
<h2 class="knew page_title">Connect with friends <span>Find and manage them here!</span></h2>

app/views/friends/_no_bookmarks.html.erb
<h3 class="mod_title">No bookmarks</h3>
<p>
You currenly do not have any profiles bookmarked. You can bookmark profiles by visiting someone's
profile and clicking on the <img src="<%= image_path('icon_star_off.gif') %>" alt="star" /> star icon
in the top, right hand corner of their profile page. <strong>Tip</strong>: you can unbookmark by
clicking the star again.
</p>

app/views/friends/_none_found.html.erb
<h3 class="mod_title">Didn't find anyone!</h3>
<p>
  We couldn't find anyone.
  Perhaps you should
  <a href="http://twitter.com/home?status=There's+this+site+@failings+that+lets+your+friends+give+you+completely+anonymous+feedback.+ha!+http%3A%2F%2Ffailin.gs%2F">tweet about us</a> and tell them to join!
</p>
<p>
  You could also <a href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Ffailin.gs&src=sp">mention us on Facebook</a>
</p>

app/views/friends/_sub_nav_nav.html.erb
<ul class="navigation">
  <%= content_tag :li, link_to_unless_current("Bookmarks", bookmarks_friends_path), class: ("active" if current_page?(bookmarks_friends_path)) %>
  <%= content_tag :li, link_to_unless_current("Twitter", twitter_friends_path), class: ("active" if current_page?(twitter_friends_path)) %>
  <%= content_tag :li, link_to_unless_current("Facebook", facebook_friends_path), class: ("active" if current_page?(facebook_friends_path)) %>
  <%# content_tag :li, link_to_unless_current("Email Contacts", email_friends_path), class: ("active" if current_page?(email_friends_path)) %>
</ul>

app/views/friends/_twitter_friend.html.erb
<% div_for twitter_friend do %>
  <%= link_to avatar_for(twitter_friend, size: 32), profile_path(twitter_friend) %>
  <%= link_to twitter_friend.login, profile_path(twitter_friend), :class => "profile_link" %>
  <span>
    (<a href="http://twitter.com/<%= twitter_friend.twitter_screen_name %>" rel="external">@<%= twitter_friend.twitter_screen_name %></a>)
    <%= render partial: "failings/bookmark", object: twitter_friend %>
  </span>
<% end %>

app/views/friends/bookmarks.html.erb
<% title "Find your friends on Failin.gs" %>
<%= render "friends_headline" %>
<div class="sub_nav">
  <%= render "sub_nav_nav" %>
  <div id="sub_nav_body" class="sub_nav_body">
    <% if current_user.bookmarked.any? %>
      <h3 class="mod_title">Your current bookmarks</h3>
      <ul class="bookmarks">
        <%= render partial: "bookmark", collection: current_user.bookmarked %>
      </ul>
    <% else %>
      <%= render "no_bookmarks" %>
    <% end %>
  </div>
</div>

app/views/friends/email.html.erb
<% title "Find your friends on Failin.gs" %>
<%= render "friends_headline" %>
<div class="sub_nav">
  <%= render "sub_nav_nav" %>
  <div class="sub_nav_body">
    <h3 class="mod_title">Scan your address book</h3>
    <p>
      Curious about who in your email address book is on failin.gs? Our look-up tool makes
      it easy to find them and leave them anonymous feedback! We don't store this information.
      We just parse the data the API returns to us and display it to you.
    </p>
    <p class="small">Supported email networks are <strong>Gmail</strong>, <strong>Yahoo!</strong>, and <strong>Microsoft Live</strong>.</p>
    <% form_tag method: :get do %>
      <fieldset>
        <%= label_tag "email", "Email address:" %>
        <%= text_field_tag "email", current_user.email, type: "email" %>
        <%= submit_tag "Go!" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/friends/facebook.html.erb
<% title "Find your friends off Failin.gs" %>
<%= render "friends/friends_headline" %>
<div class="sub_nav">
  <%= render "friends/sub_nav_nav" %>
  <div class="sub_nav_body facebook_finder">
    <% if current_user.facebook? %>
      <% if @friends.none? %>
        <%= render "none_found" %>
      <% else %>
        <p>We found the following matches.</p>
        <h3 class="mod_title">Facebook Friends</h3>
        <ul>
          <%= render partial: "facebook_friend", collection: @friends %>
        </ul>
      <% end %>
    <% else %>
      <p>
        You don't have a Facebook account linked with your failin.gs account.
        Log in below to find your friends off failin.gs!
      </p>
      <%= facebook_login %>
    <% end %>
  </div>
</div>

app/views/friends/flickr.html.erb
<% title "Find your friends on Failin.gs" %>
<%= render "friends_headline" %>
<div class="sub_nav">
  <%= render "sub_nav_nav" %>
  <div class="sub_nav_body">
    <h3 class="mod_title">Check your Flickr Contacts</h3>
    <p>
      Using the magic of open API, we can also see which of your flickr photo buddies are
      using failin.gs! Just put your username in the field below and we'll link up your
      account.
    </p>
    <form>
      <fieldset>
        <label for="flickr_user">Flickr Username:</label>
        <input type="text"/>
        <input type="submit" value="Go!"/>
      </fieldset>
    </p>
  </div>
</div>

app/views/friends/index.html.erb
<% title "Find your friends on Failin.gs" %>
<%= render "friends_headline" %>
<div class="sub_nav">
  <%= render "sub_nav_nav" %>
  <div class="sub_nav_body">
    <h3 class="mod_title">Find your friends!</h3>
    <p>
      We understand you're probably eager to find the people you know that have failin.gs accounts.
      We want to make it as easy as possible for you to accomplish this.
    </p>
    <p>
      Choose one of the methods above to find your friends.
    </p>
    <p>
      <strong>Choose an option above to get started!</strong>
    </p>
  </div>
</div>

app/views/friends/twitter.html.erb
<% title "Find your friends on Failin.gs" %>
<%= render "friends_headline" %>
<div class="sub_nav">
  <%= render "sub_nav_nav" %>
  <div class="sub_nav_body twitter">
    <% if current_user.twitter? %>
      <% if @friends.none? && @followers.none? %>
        <%= render "none_found" %>
      <% else %>
        <p>We found the following matches.</p>
        <h3 class="mod_title">People you follow</h3>
        <% if @friends.any? %>
          <%= render partial: "twitter_friend", collection: @friends %>
        <% else %>
          <p>No one you're following is on failin.gs!</p>
        <% end %>

        <h3 class="mod_title">Your Followers</h3>
        <% if @followers.any? %>
          <%= render partial: "twitter_friend", collection: @followers %>
        <% else %>
          <p>None of your followers are on failin.gs!</p>
        <% end %>
      <% end %>
    <% else %>
      <p>
        You don't have a Twitter account linked with your failin.gs account.
        Log in below to find which of your followers and followees are on failin.gs!
      </p>
      <%= twitter_login %>
    <% end %>
  </div>
</div>