config/routes.rb
FailinGs::Application.routes.draw do
  resource :user_session, except: :update
  get "login", to: "user_sessions#new", as: :login
  match "logout", to: "user_sessions#destroy", method: :delete, as: :logout

  match 'auth/failure',            to: 'authentications#failure'
  match 'auth/:provider/callback', to: 'authentications#callback'
  match 'auth/:provider/unlink',   to: 'authentications#unlink'
  match 'auth/:provider/destroy',  to: 'authentications#destroy',
    as: :auth_delete

  resource :account, controller: "users", only: %w(create edit update destroy) do
    get  "unsubscribe" => "users#unsubscribe",  as: :unsubscribe
    post "unsubscribe" => "users#unsubscribed", as: :unsubscribed
  end
  get  "account" => redirect("/account/edit")

  resources :preferences

  resource :password, only: %w(new create edit update destroy)

  scope "profile/:login" do
    resources :failings, only: %w(create show) do
      member do
        put :knew
        put :no_idea
        put :disagree
      end

      resources :comments, only: %w(create) do
        resource :abuse, only: %w(create)
      end
      resource :vote, only: %w(create)
      resource :abuse, only: %w(create)
    end
  end

  resources :friends, only: %w(index create destroy) do
    collection do
      get :bookmarks
      get :twitter
      get :facebook
      # get :email
    end
  end

  resource :invitation, only: %w(new create)
  get "invitation/search", to: "invitations#search", as: :search

  resource :share, only: %w(new create)
  resource :email, only: %w(create)

  get "profile/:login(.:format)", to: "failings#index", as: :profile
  get "profile/:login/failings" => redirect("/profile/%{login}")

  get "pages/:action", to: "pages", action: /[a-z-]+/, as: :page

  # get "javascripts/:action.:format" => "javascripts"
  get "stylesheets/:action.:format" => "stylesheets"

  mount Resque::Server.new, at: 'resque'

  root to: "pages#root"

  get ":login" => redirect("/profile/%{login}")
end

app/views/notifier/_footer.html.erb
  </div>
  <div id="failings_email_footer">
    <p>
      <% if @user %>
        You've received this email because you have an account at
        <%= link_to "failin.gs", root_url %>.<br/>
        If you would like to stop receiving emails, just
        <%= link_to "click here", unsubscribe_account_url(single_access_token: @user.single_access_token) %>.
      <% else %>
        You've received this email because someone with an account at
        <%= link_to "failin.gs", root_url %> thought it may interest you.<br/>
        You have not been subscribed to a mailing list and do not have to take
        any action to unsubscribe.
      <% end %>
    </p>
  </div>
</div>

app/views/notifier/_header.html.erb
<style type="text/css">
  #failings_email {
    font-family:Helvetica, Arial;
    background:#c1d2ee;
    padding:10px;
  }
  #failings_email #failings_email_body {
    background:#fff;
    border:1px solid #aaa;
    padding:10px;
    margin:10px;
  }
  #failings_email #failings_email_footer {
    padding:10px;
  }
  #failings_email #failings_email_footer p {
    font-size:11px;
    margin:0;
    padding:0;
  }
</style>
<div id="failings_email">
  <img src="http://failin.gs/images/logo_0.png" alt="failin.gs!" />
  <div id="failings_email_body">
    <h2>Hello!</h2>

app/views/notifier/_header.text.plain.html.erb
failin.gs (don't worry, nobody's perfect)

app/views/notifier/new_comment.html.erb
<%= render "header" %>
<p>Hey <%= @user.login %>,</p>

<p>Someone had something to say about this failing:</p>

<p><%= @comment.failing.about %></p>

<p>They said:</p>

<p><%= @comment.text %></p>

<p>Link: <%= link_to @url, @url %></p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_comment.text.html.erb
<%= render "header" %>
<p>Hey <%= @user.login %>,</p>

<p>Someone had something to say about this failing:</p>

<p><%= @comment.failing.about %></p>

<p>They said:</p>

<p><%= @comment.text %></p>

<p>Link: <a href="<%= profile_url(@user) %>"><%= profile_url(@user) %></a></p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_failing.text.html.erb
<%= render "header" %>
<p>Hey <%= @user.login %>,</p>

<p>Someone has added feedback to your profile!  You might have something to work on:</p>

<%= simple_format @failing.about %>

<p>Link: <%= link_to profile_url(@user, anchor: @failing), profile_url(@user, anchor: @failing) %></p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_invitation.plain.erb
<%= render "header" %>
Hello!

One of your friends has requested that you create an account at http://failin.gs!

Failin.gs is a website that allows you to sign up and let your friends leave anonymous feedback on you, so someone obviously has something to say to you.

Curious?  Sign up for a free account and the person that requested your feedback will be notified to populate your profile with their feedback.

We all want to improve, don't we?

Register here:

  <%= login_url(invited: @invitation.email) %>

If you do not wish to register, you don't need to do anything.  Just ignore this email.  We did not store your email address and will not contact you again.

From your friends at failin.gs!
<%= render "footer" %>

app/views/notifier/new_reply.plain.erb
<%= render "header" %>
Hey <%= @user.login %>,

<%= @someone %> replied to this failing you participated in:

<%= @comment.failing.about %>

They said:

<%= @comment.text %>

Link: <%= @url %>

From your friends at failin.gs!
<%= render "footer" %>

app/views/notifier/new_share.html.erb
<%= render "header" %>
<p>You've been invited to leave anonymous feedback on your friend, <%= @inviter.name.presence || @inviter.email %>, using a website called failin.gs -- a completely anonymous way for people to tell each other what they could improve upon!</p>

<%- if @message.present? -%>
<p>They said:</p>

<p><em>&ldquo;<%= @message %>&rdquo;</em></blockquote>
<%- end -%>

<p>This person obviously values your opinion, so do drop by and enter a few words. Your identity will not be revealed and in fact, you won't even be asked to register to leave a comment for them.</p>

<p>Their profile is here:</p>

<p><%= link_to profile_url(@inviter), profile_url(@inviter) %></p>

<p>Thank you and have a great day.</p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_share.plain.erb
<%= render "header" %>
Hello!

You've been invited to leave anonymous feedback on your friend, <%= @inviter.name.presence || @inviter.email %>, using a website called failin.gs -- a completely anonymous way for people to tell each other what they could improve upon!

<%- if @message.present? -%>
They said:

"<%= @message %>"

<%- end -%>

This person obviously values your opinion, so do drop by and enter a few words. Your identity will not be revealed and in fact, you won't even be asked to register to leave a comment for them.

Their profile is here:

  <%= profile_url(@inviter) %>

Thank you and have a great day.
From your friends at failin.gs!
<%= render "footer" %>

app/views/notifier/new_share.text.html.erb
<%= render "header" %>
<p>Hello!</p>

<p>You've been invited to leave anonymous feedback on your friend, <%= @inviter.login %> using a website called failin.gs -- a completely anonymous way for people to tell each other what they could improve upon!</p>

<p>This person obviously values your opinion, so do drop by and enter a few words. Your identity will not be revealed and in fact, you won't even be asked to register to leave a comment for them.</p>

<p>Their profile is here:</p>

<p><a href="<%= profile_user(@inviter) %>"><%= profile_user(@inviter) %></a></p>

<p>Thank you and have a great day.</p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_user.text.html.erb
<%= render "header" %>
<p>Hey <%= @user.login %>,</p>

<p>Welcome to failin.gs!</p>

<p>What next?  It's important to get your profile out there!</p>

<p>Your profile URL is <a href="<%= profile_url(@user) %>"><%= profile_url(@user) %></a></p>

<ul>
  <li><a href="http://twitter.com/?status=Signed%20up%20at%20@failings%20so%20my%20friends%20anonymously%20tell%20me%20what%20they%20don%27t%20like%20about%20me!%20<%= profile_url(@user) %>%20eep!">Tweet it</a></li>
  <li><a href="http://www.facebook.com/sharer.php?u=<%= profile_url(@user) %>&src=sp">Post it to Facebook</a></li>
  <li><a href="http://failin.gs/share/new">Email it to your friends</a></li>
</ul>

<p>The more exposure it gets, the more valuable your feedback! </p>

<p>We hope you enjoy using the site.</p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>

app/views/notifier/new_user.text.plain.erb
<%= render "header" %>
Hey <%= @user.login %>,

Welcome to failin.gs!

What next?  It's important to get your profile out there!

Your profile URL is <%= profile_url(@user) %>

* Tweet it
* Post it to Facebook
* Email it to your friends

The more exposure it gets, the more valauble your feedback! 

We hope you enjoy using the site.

From your friends at failin.gs!
<%= render "footer" %>

app/views/notifier/newly_invited.text.html.erb
<%= render "header" %>
<p>Hey <%= @inviter.login %>,</p>

<p>As you wished, your friend, <%= @invited.email %>, has joined failin.gs!</p>

<p>Why not let them know what they could work on?</p>

<p><a href="<%= profile_url(@invited) %>"><%= profile_url(@invited) %></a></p>

<p>From your friends at failin.gs!</p>
<%= render "footer" %>