config/routes.rb
FailinGs::Application.routes.draw do
  resource :user_session, except: :update
  get "login", to: "user_sessions#new", as: :login
  match "logout", to: "user_sessions#destroy", method: :delete, as: :logout

  match 'auth/failure',            to: 'authentications#failure'
  match 'auth/:provider/callback', to: 'authentications#callback'
  match 'auth/:provider/unlink',   to: 'authentications#unlink'
  match 'auth/:provider/destroy',  to: 'authentications#destroy',
    as: :auth_delete

  resource :account, controller: "users", only: %w(create edit update destroy) do
    get  "unsubscribe" => "users#unsubscribe",  as: :unsubscribe
    post "unsubscribe" => "users#unsubscribed", as: :unsubscribed
  end
  get  "account" => redirect("/account/edit")

  resources :preferences

  resource :password, only: %w(new create edit update destroy)

  scope "profile/:login" do
    resources :failings, only: %w(create show) do
      member do
        put :knew
        put :no_idea
        put :disagree
      end

      resources :comments, only: %w(create) do
        resource :abuse, only: %w(create)
      end
      resource :vote, only: %w(create)
      resource :abuse, only: %w(create)
    end
  end

  resources :friends, only: %w(index create destroy) do
    collection do
      get :bookmarks
      get :twitter
      get :facebook
      # get :email
    end
  end

  resource :invitation, only: %w(new create)
  get "invitation/search", to: "invitations#search", as: :search

  resource :share, only: %w(new create)
  resource :email, only: %w(create)

  get "profile/:login(.:format)", to: "failings#index", as: :profile
  get "profile/:login/failings" => redirect("/profile/%{login}")

  get "pages/:action", to: "pages", action: /[a-z-]+/, as: :page

  # get "javascripts/:action.:format" => "javascripts"
  get "stylesheets/:action.:format" => "stylesheets"

  mount Resque::Server.new, at: 'resque'

  root to: "pages#root"

  get ":login" => redirect("/profile/%{login}")
end

app/models/user.rb
class User < ActiveRecord::Base
  DEFAULT_INVITES_LEFT = 50

  # == Authlogic

  acts_as_authentic { |config|
    config.validations_scope = :state
  }


  # == Associations

  has_many :failings

  has_many :bookmarks, foreign_key: :bookmarker_id
  has_many :bookmarked, through: :bookmarks

  belongs_to :promotion
  has_one :invitation, foreign_key: :invited_id
  has_one :inviter, through: :invitation

  has_many :invitations, foreign_key: :inviter_id
  has_many :invited, through: :invitations

  has_many :shares


  # == Attributes

  attr_reader :promo_code
  attr_accessor :updating_password

  attr_accessible :login, :email, :password, :password_confirmation, :name,
    :location, :about, :question, :answer, :subscribe, :promo_code,
    :invitation_email, :private

  serialize :preferences, Hash

  # TODO: Unset 'hide_public_notice' when user goes private.
  def preferences
    self[:preferences] ||= {}
  end


  # == Validations and Lifecycle

  APP_LOGIN = "failings"
  LOGIN_LENGTH = 1..17
  validates :login, length: LOGIN_LENGTH

  RESERVED_LOGINS = %w(admin superuser moderator login logout user_session
    users account profile pages javascripts stylesheets oauth_login
    oauth_complete oauth_delete)
  validates_exclusion_of :login, in: RESERVED_LOGINS
  validates_format_of :login, with: /^[0-9a-z_]+$/i,
    message: "can only contain letters, numbers, and underscores."
  validates_presence_of :question, :answer
  validate :promotion_should_be_valid, on: :create

  validates_length_of :question, maximum: 200
  validates_length_of :answer, maximum: 100
  validates_length_of :name, maximum: 200, allow_blank: true
  validates_length_of :about, maximum: 500, allow_blank: true

  INVALID_PASSWORDS = %w(password)
  validates_exclusion_of :password, in: INVALID_PASSWORDS, allow_blank: true,
    message: "should be a little less common than that"

  validates :password, presence: true, if: :updating_password

  validate :oauth_token_should_be_unique

  if App.beta?
    validates_presence_of :invitation, unless: :promo_code?, on: :create
  end

  before_create :set_invites_left
  after_create :set_invitation


  # == AASM

  include AASM

  aasm_column :state
  aasm_initial_state :active

  aasm_state :active
  aasm_state :deleted
  aasm_state :abused

  aasm_event :delete do
    transitions to: :deleted, from: %w(active)
  end

  aasm_event :abuse do
    transitions to: :abused, from: %w(active)
  end

  aasm_event :activate do
    transitions to: :active, from: %w(deleted abused)
  end

  scope :active,  where(state: "active")
  default_scope active

  scope :deleted, with_exclusive_scope { where state: "deleted" }
  scope :abused,  with_exclusive_scope { where state: "abused" }
  scope :any,     with_exclusive_scope {}


  class << self
    def find_by_login_or_email(login_or_email)
      if login_or_email.include?("@")
        find_by_email(login_or_email)
      else
        find_by_login(login_or_email)
      end
    end
  end


  # == Public methods

  def to_param
    login
  end

  def invitation_email
    @invitation_email
  end

  def invitation_email=(email)
    unless email.blank?
      self.invitation = Invitation.find_by_email(@invitation_email = email)
    end
  end

  def email=(email)
    super
    self.invitation ||= Invitation.find_by_email(email)
  end

  def promo_code
    promotion.code if promotion
  end

  def promo_code=(promo_code)
    self.promotion = Promotion.find_by_code promo_code
  end

  def promo_code?
    !promo_code.blank?
  end

  def profile_empty?
    failings.where("state != ?", "abused").count.zero?
  end

  def twitter?
    twitter_screen_name?
  end

  def twitter
    return @twitter if defined? @twitter

    @twitter = if twitter?
      consumer = OAuth::Consumer.new App.twitter[:key],
        App.twitter[:secret], site: 'https://api.twitter.com',
        authorize_path: '/oauth/authenticate'
      OAuth::AccessToken.new consumer, oauth_token, oauth_secret
    end
  end

  def twitter_friend_ids
    return @twitter_friend_ids if defined? @twitter_friend_ids

    @twitter_friend_ids = if twitter?
      res = twitter.get "/1/friends/ids.json?user_id=#{twitter_id}"
      JSON.parse res.body
    else
      []
    end
  end

  def twitter_friends
    @twitter_friends ||= User.find_all_by_twitter_id twitter_friend_ids
  end

  def twitter_follower_ids
    return @twitter_follower_ids if defined? @twitter_follower_ids

    @twitter_follower_ids = if twitter?
      res = twitter.get "/1/followers/ids.json?user_id=#{twitter_id}"
      JSON.parse res.body
    else
      []
    end
  end

  def twitter_followers
    @twitter_followers ||= User.find_all_by_twitter_id twitter_follower_ids
  end

  def facebook?
    facebook_id?
  end

  def facebook
    return @facebook if defined? @facebook

    @facebook = if facebook?
      client = OAuth2::Client.new App.facebook[:key],
        App.facebook[:secret], site: 'https://graph.facebook.com'
      OAuth2::AccessToken.new client, facebook_token
    end
  end

  def facebook_friend_hashes
    return @facebook_friend_hashes if defined? @facebook_friend_hashes

    @facebook_friend_hashes = if facebook?
      res = facebook.get '/me/friends'
      JSON.parse(res)["data"]
    else
      []
    end
  end

  def facebook_friends
    return @facebook_friends if defined? @facebook_friends
    ids = facebook_friend_hashes.map { |f| f["id"] }
    @facebook_friends = User.find_all_by_facebook_id ids
    @facebook_friends.each { |f|
      f["facebook_name"] = facebook_friend_hashes.detect { |h|
        h["id"] == f.facebook_id
      }["name"]
    }
    @facebook_friends
  end

  def avatar_service
    @avatar_service ||= begin
      service = case preferences["avatar_service"]
      when "facebook"
        facebook? ? "facebook" : "gravatar"
      when "twitter"
        twitter? ? "twitter" : "gravatar"
      else
        "gravatar"
      end

      ActiveSupport::StringInquirer.new service
    end
  end

  def apply_auth(auth)
    return unless auth

    case auth["provider"]
    when 'facebook'
      self.facebook_id         = auth["uid"]
      self.facebook_token      = auth["credentials"]["token"]
    when 'twitter'
      self.twitter_screen_name = auth["user_info"]["nickname"]
      self.twitter_id          = auth["uid"]
      self.oauth_token         = auth["credentials"]["token"]
      self.oauth_secret        = auth["credentials"]["secret"]
    end

    self.name                          ||= auth["name"]
    self.preferences["avatar_service"] ||= auth["provider"]
  end

  def app?
    login == APP_LOGIN
  end

  private

  def set_invites_left
    self.invites_left = DEFAULT_INVITES_LEFT
  end

  def set_invitation
    if invitation
      invitation.invited_id = id
      invitation.save
    end

    if address = Email.find_by_address(email)
      address.user_id = id
      address.save
    end
  end

  def promotion_should_be_valid
    if promotion_id?
      if promo_code.present? && promotion.nil?
        errors[:promo_code] << "is invalid"
      elsif promotion.users.count >= promotion.limit
        errors[:promotion] << "has ended"
      end
    elsif App.beta? && email? && invitation.nil?
      errors[:promo_code] << "required for uninvited '#{email}'"
    end
  end

  def oauth_token_should_be_unique
    unless User.where("id <> ? AND oauth_token = ?", id.to_i, oauth_token).count.zero?
      errors[:base] << "Twitter account is already linked to another failin.gs profile."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, only: %w(edit update destroy)
  before_filter :require_no_user, only: %w(new create)

  respond_to :html

  def create
    @user = User.new params[:user]
    @user.promo_code = params[:promo_code] if params[:promo_code]
    @user.apply_auth auth
    @user_session = UserSession.new
    if @user.save
      if @user.invitation
        session[:invitation_email] = nil
        Resque.enqueue MailJob, @user.class.name, @user.id
      end

      path = auth ? edit_account_path : page_path("welcome")
      respond_with @user, location: path
    else
      render "user_sessions/new"
    end
  end

  def edit
    @user = current_user
    return unless stale? etag: [@user, form_authenticity_token], public: false
    respond_with @user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Updated!"
    end
    respond_with @user, location: profile_path(@user)
  end

  def destroy
    @user = current_user
    current_user_session.destroy
    @user.delete!
    redirect_to root_path
  end

  def unsubscribe
    @user = User.find_by_single_access_token(params[:single_access_token])
    render Rails.root.join("public/404.html"), status: :not_found unless @user
  end

  def unsubscribed
    if @user = User.find_by_single_access_token(params[:single_access_token])
      @user.update_attribute :subscribe, false
    else
      render Rails.root.join("public/404.html"), status: :not_found
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<fieldset id="signup_form">
  <%= form_for @user, :url => account_path do |f| %>
    <%= f.hidden_field :invitation_email, value: @user.invitation_email || session[:invitation_email] ||= params[:invited] %>

    <% if @user.errors.any? %>
      <%= f.error_messages %>
    <% end %>

    <%= f.label :login, "Username:" %>
    <%= f.text_field :login, maxlength: User::LOGIN_LENGTH.max %>

    <label>
      Your <strong>real</strong> last name:
      (<%= link_to "Why we ask", "#", onclick: "$('box_important').appear(); return false;" %>):
      <%= f.text_field :answer %>
    </label>

    <%= f.label :email, "Email address:" %>
    <%= f.text_field :email, type: "email", value: @user.email || session[:invitation_email] ||= params[:invited] %>

    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Twice to be sure:" %>
    <%= f.password_field :password_confirmation %>
    <p>By creating an account you agree to our very exciting <a href="/pages/terms">terms of use</a> and also agree to play nice.</p>
    <%= f.submit "Sign up!" %>
  <% end %>
  <script type="text/javascript">
    <% if session[:invitation_email] && @user.email.blank? %>
      $("user_<%= auth ? "answer" : "login" %>").focus();
    <% end %>
  </script>
</fieldset>

app/views/users/_pic_area.html.erb
<div id="pic_area" class="pic_area">
  <%= avatar_for @user, default: image_url("default_pic.png"), size: 200 %>
  <h2>Manage your picture</h2>
  <p class="small">
    You can pull your user picture from other websites. Pick a service below to link your account and use that site's picture for you.
  </p>
  <h4>Your available networks</h4>
  <dl class="avatar_services">
    <% unless @user.facebook? %>
      <dt>
        <%= link_to image_tag("facebook_setup.png"), facebook_login_path %>
      </dt>
      <dd>
        <%= link_to "Authenticate your account with Facebook", facebook_login_path %>
        <p>Use your Facebook profile pic on failin.gs.</p>
      </dd>
    <% else %>
      <dt>
        <%= link_to_unless @user.avatar_service.facebook?, facebook_image_for(@user, size: 32), preferences_path(key: "avatar_service", value: "facebook"), method: :post, remote: true %>
      </dt>
      <dd>
        <% if @user.avatar_service.facebook? %>
          <strong>Facebook icon (applied)</strong>
        <% else %>
          <%= link_to "Apply your Facebook icon", preferences_path(key: "avatar_service", value: "facebook"), method: :post, remote: true %>
        <% end %>
        <p>
          Your Facebook account is connected to failin.gs
          (<%= link_to "unlink", auth_delete_path(provider: 'facebook'), method: :delete, confirm: "Unlink your failin.gs profile from your Facebook account?" %>).
        </p>
      </dd>
    <% end %>

    <% unless @user.twitter? %>
      <dt>
        <%= link_to image_tag("twitter_setup.png"), twitter_login_path %>
      </dt>
      <dd>
        <%= link_to "Authenticate your account with Twitter", twitter_login_path %>
        <p>Use your Twitter profile pic on failin.gs.</p>
      </dd>
    <% else %>
      <dt>
        <%= link_to_unless @user.avatar_service.twitter?, tweetimage_for(@user, size: 32), preferences_path(key: "avatar_service", value: "twitter"), method: :post, remote: true %>
      </dt>
      <dd>
        <% if @user.avatar_service.twitter? %>
          <strong>Twitter icon (applied)</strong>
        <% else %>
          <%= link_to "Apply your Twitter icon", preferences_path(key: "avatar_service", value: "twitter"), method: :post, remote: true %>
        <% end %>
        <p>
          Your Twitter account is connected to failin.gs
          (<%= link_to "unlink", auth_delete_path(provider: 'twitter'), method: :delete, confirm: "Unlink your failin.gs profile from your Twitter account, '#{@user.twitter_screen_name}'?" %>).
        </p>
      </dd>
    <% end %>

    <dt>
      <%= link_to_unless @user.avatar_service.gravatar?, gravatar_for(@user, size: 32), preferences_path(key: "avatar_service", value: "gravatar"), method: :post, remote: true %>
    </dt>
    <dd>
      <% if @user.avatar_service.gravatar? %>
        <strong>Gravatar icon (applied)</strong>
      <% else %>
        <%= link_to "Apply your Gravatar icon", preferences_path(key: "avatar_service", value: "gravatar"), method: :post, remote: true %>
      <% end %>
      <p>
        No image? <a href="http://en.gravatar.com/site/signup" rel="external">Register</a> your failin.gs email address at Gravatar.
      </p>
    </dd>
  </dl>
</div>

app/views/users/_request.html.erb
<fieldset id="request_form" style="display: none;">
  We are still in private beta, so we haven't opened the doors to everyone yet,
  but if you want an invite, give us your email and we'll send you an invite
  as soon as we can.
  <%= form_for @email, url: email_path, remote: true do |f| %>
    <%= f.error_messages %>

    <%= f.label :address, "Email address:" %>
    <%= f.text_field :address, type: "email" %>

    <%= f.submit "Send" %>
  <% end %>
</fieldset>
<script type="text/javascript">
  if (window.location.search === "?request=invite") {
    $("login_form").hide();
    $("signup_form").hide();
    $("request_form").show();
    $("email_address").focus();
  }
</script>

app/views/users/edit.html.erb
<% title "Edit your account" %>
<h2 class="page_title knew">Account Settings<span>Tweak to your heart's content</span></h2>

<% unless @user.facebook? %>
  <div id="facebook_connect">
    <h3 class="mod_title">Connect with Facebook!</h3>
    <p>By connecting with Facebook you can import your photo and find your friends. We won't send any of your flaws to Facebook, so don't worry.</p>
    <p><%= facebook_login %></p>
    <a href="#" onclick="new Effect.BlindUp('facebook_connect');">Maybe later</a>
  </div>
<% end %>

<div id="user_profile" class="edit">
  <%= render "users/pic_area" %>

  <%= form_for @user, url: account_path do |f| %>
    <div class="user_details">
      <%= render "common/flash_message" %>

      <h3 class="mod_title">Your personal settings</h3>
      <%= f.error_messages %>
      <h3>Security Question</h3>
      <%#= f.label :login, "Username:" #%>
      <%#= f.text_field :login, maxlength: User::LOGIN_LENGTH.max #%>

      <%= f.label :question, "Security question: (#{link_to 'Why we ask', '#', onclick: '$("box_important").appear(); return false;'})".html_safe %>
      <%= f.text_field :question %>

      <%= f.label :answer, "Security question response:" %>
      <%= f.text_field :answer %>
      <h3>Personal Information</h3>
      <p class="small">
        Optionally, you can enter your full name, which we use
        to identify you when you send your profile through our email tool.
      </p>
      <%= f.label :name, "Your full name (not shown on your profile):" %>
      <%= f.text_field :name %>

      <%= f.label :email, "Email address (also hidden):" %>
      <%= f.text_field :email %>

      <p class="small">
        Next, provide some additional details about yourself. Be descriptive, otherwise someone
        might not know who you are.
      </p>
      <%= f.label :location, "Location:" %>
      <%= f.text_field :location %>
      <%= f.label :about, "About me:" %>
      <%= f.text_area :about, rows: 5, cols: 80, maxlength: 500, onkeyup: "return ismaxlength(this)" %>

      <%= f.submit "Save all this" %>
    </div>

    <div class="announce rounded_box">
      <h2>Additional Settings</h2>
      <p class="small">
        Here are some additional settings
        for you. You can save your changes
        at the bottom of the page.
      </p>

      <%= f.label :password, "New password:" %>
      <%= f.password_field :password, autocomplete: "off" %>

      <%= f.label :password_confirmation, "Twice to be sure:" %>
      <%= f.password_field :password_confirmation, autocomplete: "off" %>

      <h2>Private Profile</h2>

      <label class="checkbox">
        <%= f.check_box :private %>
        I'm shy. Only let me see my feedback.
      </label>

      <h2>Email notifications</h2>

      <label class="checkbox">
        <%= f.check_box :subscribe %>
        Let me know when someone posts something to my account.
      </label>

      <h2>Want to remove your account?</h2>
      <p>We'd be sad to see you go, but we understand that the truth hurts.</p>
      <blockquote class="drop_shadow">
        "I'll say. <%= link_to "Let me out", account_path, method: :delete, confirm: "Are you sure you want to do this? There is no undo and your profile will be gone forever." %>"
      </blockquote>
    </div>
  <% end %>
</div>

app/views/users/unsubscribe.html.erb
<% if @user.subscribe? %>
  <h2>Really unsubscribe?</h2>

  <p>
    You will stop receiving email notifications for your failings and those you've participated in.

    <%= button_to "Yes, really unsubscribe", unsubscribed_account_path(single_access_token: params[:single_access_token]) %>
  </p>
<% else %>
  <p>
    You're not currently subscribed to notifications at this time.
  </p>
  <p>
    To re-subscribe at any time, visit <%= link_to "your account settings", edit_account_path %>.
  </p>
<% end %>

app/views/users/unsubscribed.html.erb
<h2>Unsubscribed!</h2>

<p>
  You've successfully unsubscribed!
</p>
<p>
  To re-subscribe at any time, visit <%= link_to "your account settings", edit_account_path %>.
</p>