config/routes.rb
FailinGs::Application.routes.draw do
  resource :user_session, except: :update
  get "login", to: "user_sessions#new", as: :login
  match "logout", to: "user_sessions#destroy", method: :delete, as: :logout

  match 'auth/failure',            to: 'authentications#failure'
  match 'auth/:provider/callback', to: 'authentications#callback'
  match 'auth/:provider/unlink',   to: 'authentications#unlink'
  match 'auth/:provider/destroy',  to: 'authentications#destroy',
    as: :auth_delete

  resource :account, controller: "users", only: %w(create edit update destroy) do
    get  "unsubscribe" => "users#unsubscribe",  as: :unsubscribe
    post "unsubscribe" => "users#unsubscribed", as: :unsubscribed
  end
  get  "account" => redirect("/account/edit")

  resources :preferences

  resource :password, only: %w(new create edit update destroy)

  scope "profile/:login" do
    resources :failings, only: %w(create show) do
      member do
        put :knew
        put :no_idea
        put :disagree
      end

      resources :comments, only: %w(create) do
        resource :abuse, only: %w(create)
      end
      resource :vote, only: %w(create)
      resource :abuse, only: %w(create)
    end
  end

  resources :friends, only: %w(index create destroy) do
    collection do
      get :bookmarks
      get :twitter
      get :facebook
      # get :email
    end
  end

  resource :invitation, only: %w(new create)
  get "invitation/search", to: "invitations#search", as: :search

  resource :share, only: %w(new create)
  resource :email, only: %w(create)

  get "profile/:login(.:format)", to: "failings#index", as: :profile
  get "profile/:login/failings" => redirect("/profile/%{login}")

  get "pages/:action", to: "pages", action: /[a-z-]+/, as: :page

  # get "javascripts/:action.:format" => "javascripts"
  get "stylesheets/:action.:format" => "stylesheets"

  mount Resque::Server.new, at: 'resque'

  root to: "pages#root"

  get ":login" => redirect("/profile/%{login}")
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>failin.gs: what don't you like about me? <%= yield(:title) %></title>
  <%= csrf_meta_tag %>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  <meta name="description" content="failin.gs is a completely anonymous feedback system for people to engage their family and friends for personal critiques!">
  <meta name="keywords" content="failings, flaws, anonymous, social web, social networking, self-improvement, fun">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :prototype %>
  <%= javascript_include_tag "rails", "application", cache: true %>
  <!--[if lt IE 7]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js"></script>
  <![endif]-->
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:'ee6031c9-0523-4b0a-a452-362903ee36d0'});</script>
</head>
<body class="<%= controller.action_name %>">
  <style>
    #shutting_down {
      background:#7F1D35;
      font-size:18px;
      color:#fff;
      padding:20px 0;
      margin-bottom:40px;
      border-bottom:3px solid yellow;
    }
    #shutting_down a {
      color:yellow;
    }
  </style>
  <div id="shutting_down">failin.gs is <em>shutting down</em> on <strong>September 24, 2012</strong>. <a href="/pages/what">huh?</a></div>
  <div id="wrapper">
    <h1 id="logo" onclick="window.location.href='/'">failin.gs</h1>
    <script type="text/javascript">
      function randomize_logo() {
        $('logo').style.backgroundImage = "url('/images/logo_" + Math.floor(Math.random()*3) + ".png')";
      }
      randomize_logo();
    </script>
    <div id="container" class="rounded_box drop_shadow">
      <div id="top_links">
        <ul>
          <% if logged_in? %>
            <li class="search">
              <%= form_tag search_path, method: :get do %>
                <fieldset title="Search by email">
                  <%= text_field_tag "email_query", params[:email_query], type: "search", placeholder: "search by email", autosave: "gs.failin", results: 10 %>
                </fieldset>
              <% end %>
            </li>
            <li><%= link_to_unless_current "my profile", profile_path(current_user) %></li>
            <li><%= link_to_unless_current "settings", edit_account_path %></li>
            <li><%= link_to_unless_current "share", new_invitation_path %>
            <% if current_user.invites_left > 0 %>
              (<span id="invites_left"><%= current_user.invites_left %></span> invites)</li>
            <% end %>
            <li><%= link_to_unless_current "friends", bookmarks_friends_path %></li>
            <li><%= link_to "log out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to_unless_current "log in", login_path %></li>
          <% end %>
        </ul>
      </div>
      <p class="social_links">follow us on <a href="http://twitter.com/failings">twitter</a>, <a href="http://facebook.com/failings">facebook</a></p>
      <div class="body">
        <div id="<%= controller.controller_name %>" class="<%= controller.action_name %>">
          <%= yield %>
        </div>
      </div>
    </div>
    <div id="footer">
      &copy; <%= Date.today.year %> - <a href="/pages/terms">Terms of Use &amp; Privacy</a>
    </div>
  </div>
  <div class="floating_box rounded_box drop_shadow" id="box_important" style="display: none;">
    <p><strong>failin.gs</strong> is a community where you can have your friends
    anonymously critique you.</p>

    <p>It's important, though, to make sure that the people who leave you
    feedback actually do know who you are.</p>

    <p>When someone leaves feedback on you, they will be asked for your security
    question. The default is your last name. You can change this later in your settings.</p>

    <p>You'll have a chance to respond to everyone's feedback. You can even flag
    things that you think are fake.</p>

    <p>Don't worry. Your name will not be viewable to anyone.</p>

    <%= link_to "x", "#", onclick: "$('box_important').fade(); $('lastname').focus(); return false;", class: "close" %>
  </div>
  <div class="floating_box rounded_box drop_shadow" id="email_preview" style="display: none;">
    <p>Hello!</p>
    <p>
      You've been invited to leave anonymous feedback on your friend, [your name here] using
      a website called failin.gs -- a completely anonymous way for people to tell each other
      what they could improve upon!
    </p>
    <div id="custom_email_preview" style="display: none;">
      <p>They said:</p>
      <p>&ldquo;<em id="custom_email_preview_message"></em>&rdquo;</p>
    </div>
    <p>
      This person obviously values your opinion, so do drop by and enter a few words. Your
      identity will not be revealed and in fact, you won't even be asked to register to
      leave a comment for them.
    </p>
    <p>
      Their profile is here: http://failin.gs/profile/[username]
    </p>
    <p>
      Thank you and have a great day.<br/>
      The failin.gs gang
    </p>
    <%= link_to "x", "#", onclick: "$('email_preview').fade(); return false;", class: "close" %>
  </div>
  <script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>
  <script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-12415011-1");
  pageTracker._trackPageview();
  } catch(err) {}</script>
</body>
</html>